Library files from https://github.com/jrosain/Homotopy-Finiteness/
JonasHoefer/poset-type-theory pull request #4
Opened 2024-07-29 10:01 UTC by jrosain

Organized the files from my internship in a coherent file system & split up the prelude to integrate it seamlessly.

Added a file `Everything.ctt` for testing purposes. It should typecheck 1334 definitions.

2024-08-01 21:40 UTC, JonasHoefer requested changes
Otherwise, the PR looks very good!

2024-08-01 21:40 UTC, JonasHoefer commented on library/Foundation/.#Paths.ctt
I think this file is not supposed to be part of the PR.

2024-08-02 10:13 UTC, jrosain commented on library/Foundation/.#Paths.ctt
That's right, it has been removed in 36ef90f.

2024-08-02 14:15 UTC, JonasHoefer approved these changes
Looks good now. Thank you very much for all your hard work on the project!

2024-08-02 14:15 UTC, merged